### PR TITLE
Create hotelmanagementsystem.cpp

### PR DESCRIPTION
**Pull request by adityaharsh2001**

### CODE REVIEW

**Comment by aditya109** [comment]
Hi @adityaharsh2001 ! I want you to do 2 things:
1. Rename the ` hotelmanagementsystem.cpp` to `HotelManagementSystem.java` and put it inside `HotelManagementSystem` folder inside C++ folder.
2. Open separate issue for this and link it here.  Follow this [template](https://github.com/aditya109/git-osp-for-beginners/issues/new?assignees=&labels=Hacktoberfest%2C+good+first+issue&template=programming-question.md&title=%5BQuestion%5D).

**Review by aditya109 — CHANGES_REQUESTED** [review]
Please check my comments.

**Comment by adityaharsh2001** [comment]
@aditya109 but why to rename a cpp file to java..🤔🤔

**Comment by aditya109** [comment]
> @aditya109 but why to rename a cpp file to java..🤔🤔

My bad! I guess that happens while viewing too many PRs. Will merge this one!

**Comment by aditya109** [comment]
Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Pull request merged**
