### PR TITLE
Implementation of Luhn's Algorithm in Python based on Java code and Updated it's README.md

### PR DESCRIPTION
**Pull request by hryxna**
Hey, @aditya109 and @Ajordat would you mind checking this implementation of mine in python 😅 ?
It's addressing the closed issue #178 
If it's valuable then do consider adding this contribution to your repo as well 😄.

### CODE REVIEW

**Comment by hryxna** [comment]
Also, quick suggestion @aditya109  when merging do a squash merge 😬

**Review by aditya109 — APPROVED** [review]
lgtm

**Comment by aditya109** [comment]
Hi @hryxna ! Great work on your PR. Always try raising PRs in open source projects from a local branch, not master.

**Comment by hryxna** [comment]
@aditya109 I didn't understand what you meant by from local branch instead of master 😅.
Could you please elaborate?

If you are advising me to get a clone to the pc and then raise a PR or something else 😅.

**Comment by Ajordat** [comment]
Hello!

Sorry for not replying on time. The implementation looks good to me.

Also, I think that @aditya109 meant that you create a branch on your forked repo instead of merging from master.

**Comment by hryxna** [comment]
Oh, now I get it thanks @Ajordat for clearing my doubt 😄.
ok, I'll keep that in mind @aditya109 👍🏻.

**Pull request merged**
