### PR TITLE
added more conditions to make the program precise

### PR DESCRIPTION
**Pull request by varanasiroshan2001**

### CODE REVIEW

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @varanasiroshan2001 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Comment by varanasiroshan2001** [comment]
why in hacktober its not counting this pr as it was success plz check
weather u have correct labels and topic included so it is valid for pr for
hacktober fest looking to contribute more

**Pull request merged**
