### PR TITLE
Added the Luhn's Algorithm

### PR DESCRIPTION
**Pull request by hryxna**
Hello @aditya109 😄 
I have added the program as I told you earlier about.
kindly check it.
if it's all good add this contribution of mine to your repo 😃.
Also before this pr, I had updated the fork of mine with from the main.
so I would suggest you to squash all the commits together and then merge 😅.

### CODE REVIEW

**Comment by aditya109** [comment]
Hi @hryxna ! This seems like a `good-first-issue`. Would you mind opening one in relation to this ? I would gladly issue this to you and link the issue here. Follow this [template](https://github.com/aditya109/git-osp-for-beginners/issues/new?assignees=&labels=Hacktoberfest%2C+good+first+issue&template=programming-question.md&title=%5BQuestion%5D). If you don't want to, it's fine, just tell me I will merge this PR.

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by hryxna** [comment]
Sure @aditya109 it would be a good idea to open a new issue 😃.
I have opened a new issue in relation to this kindly check it.
if there's anything I haven't covered then let me know 😁.

**Comment by hryxna** [comment]
Hey, @aditya109 looks like we are getting a response from the contributors on the issue I made.
should we let them add it to the different languages folder or should we make a dedicated folder to it? 🤔

Also, I would like to assign the guys who have made the pr for issue #178 would you mind if I ask you to do this 😅.

**Review by aditya109 — APPROVED** [review]
LGTM

**Pull request merged**
