### PR TITLE
Adding python solution for AddTwoNumber issue #205

### PR DESCRIPTION
**Pull request by asheemchhetri**
Signed-off-by: Asheem Chhetri <achhetri@alumni.purdue.edu>
-Added soltuion to for addTwoNumbers
-Added test cases in test folder
-Added __init__.py, to fix the import structure while testing
-Added __pycache__, *.pyc in gitignore, to make the git add stage clutter free

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @asheemchhetri ! Great work on the Question, but could you please remove empty  `__init__.py` from `Python` and `root` folder, since it is not required for im/explicit imports. :)

**Comment by asheemchhetri** [comment]
@aditya109 sure! I was actually thinking about it later, as the repo is more about proposing solutions in various lang. thus having __init__.py can confuse other people. I will add that change, and remove the tescases as it needs it explicitly. Thanks!

**Review by aditya109 — APPROVED** [review]
lgtm

**Comment by aditya109** [comment]
Thanks for quick take on the issue ! Great work on your PR ! If you have not please consider starring this repo to encourage further contributions.

**Comment by asheemchhetri** [comment]
> Thanks for quick take on the issue ! Great work on your PR ! If you have not please consider starring this repo to encourage further contributions.

Absolutely @aditya109 I will slot out some time to contribute here. But I am just curious regrading the bigger scope of this project. Are you planning to host like some interview questions or practice questions for other learners?

**Pull request merged**
