### PR TITLE
2 Strings anagram or not

### PR DESCRIPTION
**Pull request by Kaustav96**
#83 
#39

### CODE REVIEW

**Comment by Kaustav96** [comment]
will this issue be closed or is there any changes to be made?

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @Kaustav96 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Comment by Kaustav96** [comment]
> Hi @Kaustav96 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

Will do @aditya109 👍

**Pull request merged**
