### PR TITLE
added code for checking duplicate in a sorted array

### PR DESCRIPTION
**Pull request by devjak26**

### CODE REVIEW

**Comment by devjak26** [comment]
#468

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @devjak26 ! Please read CONTRIBUTING.md before raising a PR. Create appropriate folder structure and place your file there.

**Comment by devjak26** [comment]
#468

**Review by aditya109 — APPROVED** [review]
LGTM ! Great work on your PR 👏 ! If you have not please consider starring⭐ this repo to encourage further contributions.

**Pull request merged**
