### PR TITLE
Added palindrome checker in java

### PR DESCRIPTION
**Pull request by a-ayush19**
Solved issue #456

### CODE REVIEW

**Comment by a-ayush19** [comment]
@aditya109 hey can you check this PR out and merge it if it solves the issue

**Review by aditya109 — CHANGES_REQUESTED** [review]
Please do the following file changes according to the expectation according to CONTRIBUTING.md. 
Create a problem folder in the Java folder and  place your `.java` file inside it.

**Comment by a-ayush19** [comment]
@aditya109 hey, I have made the changes as requested, I've added the file in the folder, kindly have a look

**Review by aditya109 — APPROVED** [review]
LGTM ! Great work on your PR 👏 ! If you have not please consider starring⭐ this repo to encourage further contributions.

**Pull request merged**
