### PR TITLE
Added Luhn's Algorithm in C++.

### PR DESCRIPTION
**Pull request by deep1112002**
Added Luhn's Algorithm in C++.
 Signed-off-by: Deep Thakkar <deep1112002@gmail.com>

### CODE REVIEW

**Comment by hryxna** [comment]
Hey @deep1112002 I would suggest you add the comments and necessary explanation to your code
Also i quite didn't understand the 48 in { int add=(cardno[i]-48)*2; } 😅.

Also, I think you missed out on the part of checking the first digits of entered credit card no. to validate it 😅.
Was it for general implementation or you forgot?

Let's see what @aditya109 would say

**Comment by deep1112002** [comment]
I actually did it for general purpose. And as I have used string as input so i cannot have the value of the entered digits directly. I will have the ASCII of the entered digits. So as the ascii of 0 is 48 i subtracted 48 from each character digit. I will add comments and again send a pull request. Thanks 😊

**Comment by deep1112002** [comment]
I also referred the explanation on geeks for geeks and made my code according to that. https://www.geeksforgeeks.org/luhn-algorithm/

**Comment by hryxna** [comment]
@deep1112002 i understood the 48 now thanks for clearing my doubt
I was thinking that this code can be optimised
Would you mind optimising it 😅?

**Comment by hryxna** [comment]
Also @deep1112002 don't make a new PR just make the changes to existing code it will be directly displayed into your current PR 😄

**Comment by aditya109** [comment]
I don't think I need to intervene here ! @hryxna and @deep1112002 you guys seem to be having fun. Happy hacking!

**Comment by hryxna** [comment]
> I don't think I need to intervene here ! @hryxna and @deep1112002 you guys seem to be having fun. Happy hacking!

Hahahaha 😂

**Comment by deep1112002** [comment]
Thank you. And as  @hryxna has suggested I added comments to the code. Thanks

**Comment by deep1112002** [comment]
I have one doubt can i contribute to this repo more than one time for Hacktoberfest?? Will it be counted??

**Comment by deep1112002** [comment]
I will optimise it for sure.

**Comment by hryxna** [comment]
I'm not quite sure about the question you're asking regarding the multiple PR for hacktoberfest @deep1112002 😅

But if you want to contribute for the repo then feel free to do so.😄

**Comment by aditya109** [comment]
Hi @deep1112002 @hryxna ! Would you guys mind confirming if this PR is merge ready.?

**Comment by deep1112002** [comment]
I will complete it in half an hour

**Comment by deep1112002** [comment]
I think it is right now. I could have optimised it but then the code would look complicated and someone might not have been able to understand it. So the one already uploaded by me maybe good enough but if you have another approach then you can tell me.

**Review by hryxna — APPROVED** [review]
Looks good to me I checked with a couple of credit cards no. the program is working as intended 👍🏻 
merge it @aditya109.

**Comment by hryxna** [comment]
> I think it is right now. I could have optimised it but then the code would look complicated and someone might not have been able to understand it. So the one already uploaded by me maybe good enough but if you have another approach then you can tell me.

Don't worry everyone will understand this one, if you find something way simpler than this then update it maybe later.
Well as of now it's all good to go.
keep it up 😄.

**Review by aditya109 — APPROVED** [review]
LGTM

**Pull request merged**
