### PR TITLE
Create differentRunsScoredByBatsmenInCricket

### PR DESCRIPTION
**Pull request by reejuBhattacharya**
runsScoredByBatsman code written in java. I am a newbie so any and all suggestions and improvements will be appreciated.

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @reejuBhattacharya ! Great Work ! Just change the folder containing your java file to the name of your java file. For instance, make it `differentRunsScoredByBatsmenInCricket `.

**Comment by aditya109** [comment]
Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by reejuBhattacharya** [comment]
Ok, thanks for the reply!

**Comment by aditya109** [comment]
Unfortunately, I can't merge this PR, since you haven't addressed the changes  but I am labelling this PR as `hacktoberfest-accepted` which carries the same value. Also, if you have not, consider starring this repo.

**Pull request closed without merging**
