### PR TITLE
Reverse integer using C

### PR DESCRIPTION
**Pull request by SAKSHI2569**
Reverse integer using C

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @SAKSHI2569 ! It seems your program file doesn't have an extension. Also, please follow the guidelines while raising the PR. Put your program inside appropriate folders.

**Comment by yoki-07** [comment]
I want to contribute in this by providing the code in Cpp. Please assign me this.

**Comment by yoki-07** [comment]
@SAKSHI2569

**Comment by aditya109** [comment]
> I want to contribute in this by providing the code in Cpp. Please assign me this. @aditya109

Hi @yoki-07 ! I think the issue is closed. But what you could do is raise a PR, and tag it as `refactor`. Reference the issue on your PR.

**Comment by aditya109** [comment]
Unfortunately I can't merge this PR, as this PR does not comply the `CONTRIBUTING.md`, but to acknowledge your contribution I have marked this PR as `hacktoberfest-accepted` which carries the same value. Please consider starring the repo, if you have not already to encourage further contributions.

Closing this PR.

**Pull request closed without merging**
