### PR TITLE
Python Patterns

### PR DESCRIPTION
**Pull request by Hinal-Srivastava**
Added two a little more than basic questions:
1 . Diamond of *
2. Alphabetically arranged equilateral triangle

Issue [#3](https://github.com/aditya109/git-osp-for-beginners/issues/3 )

### CODE REVIEW

**Comment by aditya109** [comment]
Hi @Hinal-Srivastava Would you like to keep this PR open ? Or keep working on this. If you would like to keep working on this PR, please either change the title to `WIP : Python Patterns`, or convert this to a draft PR.
When you are ready for this PR to be reviewed, then change the title back. Thanks !

**Comment by aditya109** [comment]
Also please link the issue you are working on.

**Comment by Hinal-Srivastava** [comment]
> Hi @Hinal-Srivastava Would you like to keep this PR open ? Or keep working on this. If you would like to keep working on this PR, please either change the title to `WIP : Python Patterns`, or convert this to a draft PR.
> When you are ready for this PR to be reviewed, then change the title back. Thanks !

I have put in the ones I wanted to. For the rest you can open this as a separate issue so other can contribute to it.

**Comment by Hinal-Srivastava** [comment]
> Also please link the issue you are working on.

Done

**Pull request merged**
