### PR TITLE
Create IsYourPasswordStrong.py

### PR DESCRIPTION
**Pull request by Aashrut**
I have tested the code myself on different cases and is working absolutely fine. And also it uses simple functions and some string methods to solve the problem . So it is also beginner-friendly.

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @Aashrut ! Can you put your code inside a folder called `IsYourPasswordStrong`.

**Comment by aditya109** [comment]
Please consider starring the repo if possible.

**Review by aditya109 — CHANGES_REQUESTED** [review]
Please open an issue relative to this PR, claim it and then link that issue here. Follow this [template](https://github.com/aditya109/git-osp-for-beginners/issues/new?assignees=&labels=Hacktoberfest%2C+good+first+issue&template=programming-question.md&title=%5BQuestion%5D).

**Comment by Aashrut** [comment]
Hey, I have made that issue #124 . And added program for that. I have also moved the program to the new folder.

**Review by aditya109 — APPROVED** [review]
lgtm

**Pull request merged**
