### PR TITLE
Create a Zoo with animals #267

### PR DESCRIPTION
**Pull request by Yasas4D**
Created the Zoo management Application
screenshot_17
screenshot_18

### CODE REVIEW

**Review by aditya109 — COMMENTED** [review]
Your PR has some conflicts. Please go ahead and resolve them.

**Review by aditya109 — CHANGES_REQUESTED** [review]
resolve your conflicts

**Comment by Yasas4D** [comment]
okay sure

**Comment by Yasas4D** [comment]
Conflicts resolved

**Review by aditya109 — APPROVED** [review]
Thanks for quick update. LGTM.

**Comment by aditya109** [comment]
Hi @Yasas4D ! Great work on your PR. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by Yasas4D** [comment]
Hi @aditya109  ! I'm extreamly happy to contribute to this project. and I'm willing to give my support in further issues. Thank you

**Pull request merged**
