### PR TITLE
Python_Art

### PR DESCRIPTION
**Pull request by Hashininirasha**
Turtle is a pre-installed Python library that enables users to create pictures and shapes by providing them with a virtual canvas. The onscreen pen that you use for drawing is called the turtle and this is what gives the library its name

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @Hashininirasha ! Would you mind writing a small description as to what you are trying to do here ? Would be great if you opened issue relative to it or linked an already available issue. Also please consider starring the repo if possible.

**Comment by Hashininirasha** [comment]
> Hi @Hashininirasha ! Would you mind writing a small description as to what you are trying to do here ? Would be great if you opened issue relative to it or linked an already available issue. Also please consider starring the repo if possible.

turtle is a pre-installed Python library that enables users to create pictures and shapes by providing them with a virtual canvas. The onscreen pen that you use for drawing is called the turtle and this is what gives the library its name

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @Hashininirasha ! Great work on the PR. I would want you to make couple of changes.

1. Please change the name of your program to something meaning full.
2. Make a directory with the same name and put your file inside of it.
3. Put this folder under `Python` directory inside `Programming` directory.
4. Put necessary comments in your program to improve readability.

**Comment by aditya109** [comment]
Hi @Hashininirasha ! Unfortunately since you're are unable to make suggested changes, I am closing this PR now. Hope you raise a fresh PR for the same. Happy Hacking !

**Pull request closed without merging**
