### PR TITLE
Solved Roots of Quadratic Equation and Prime Number upto N in python

### LINKED ISSUE #53: Roots of the Quadratic Equation | Prime Numbers upto N | Python
Program1 - which takes inputs of the coefficients of a Quadratic Equation and outputs roots of the equation. 
Program2 - which takes input of a number N and outputs all Prime Numbers upto N.

### LINKED ISSUE #131: Roots of Quadratic Equation | Python
Program - which takes inputs of the coefficients of a Quadratic Equation and outputs roots of the equation.
For ex- the format of quadratic eq is ' a*x^2 + b*x + c '
Program takes input the value of a,  b, c and gives out roots the eq.

### LINKED ISSUE #133: Prime Numbers Upto N | Python
Program  - which takes input of a number N and outputs all Prime Numbers upto N.

### PR DESCRIPTION
**Pull request by vijay5158**
Fixes #131 
Fixes #133 
Solved two Maths problem in Python.

### CODE REVIEW

**Comment by vijay5158** [comment]
@aditya109 Please check it.

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @vijay5158  I want you to do 2 things:
1. Rename the file by Camel Casing it and put each file inside a folder with name of the file inside C++ folder. So `prime_numbers_upto_n.py` could be renamed to `PrimeNumbersUptoN` and could be placed in `PrimeNumbersUptoN` folder inside Python.
2. Open separate issue for this and link it here.  Follow this [template](https://github.com/aditya109/git-osp-for-beginners/issues/new?assignees=&labels=Hacktoberfest%2C+good+first+issue&template=programming-question.md&title=%5BQuestion%5D).

**Comment by vijay5158** [comment]
@aditya109 changed the files name and its placed them inside the folder of their name in python folder. 
I already opened a issue related to these questions and I was also assigned, here is the issue which fixes #53

**Comment by vijay5158** [comment]
Fixes #133

**Comment by vijay5158** [comment]
Fixes #131

**Comment by vijay5158** [comment]
Closes #131

**Comment by vijay5158** [comment]
Changed file names and placed them in the folder of their name in python folder, 
And opened two separate issues for these two problems (#131 #133 )

**Comment by aditya109** [comment]
Hi @vijay5158 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Pull request merged**
