### PR TITLE
Solved highest scorer problem in C++

### PR DESCRIPTION
**Pull request by mohitrathor98**
Please let me know for any further requirements.  #26

### CODE REVIEW

**Comment by aditya109** [comment]
Hi @mohitrathor98 please change the folder name to `Problem3` from `Problem2`. Also please claim the related issue by commenting in the issue conversation and link that issue. 
 A humble request to star this repo to encourage further contributions.

**Comment by mohitrathor98** [comment]
Hi! can you please re-assign me.

**Comment by mohitrathor98** [comment]
Hi! I have updated the directory name to Problem3

**Comment by aditya109** [comment]
Hi @mohitrathor98 I can't merge this PR, because someone pushed a PR before you, but I am labelling this PR as `hacktoberfest-accepted` which carries the same value. 
Also, if you have not, consider starring this repo.

**Pull request merged**
