### PR TITLE
Added Java Solution :  Rotate Array left and right  by k times . (Issue  #243)

### PR DESCRIPTION
**Pull request by hrj-star**
Added code in Java to solve issue #243. 

Objective : Given an array, return both resulting arrays when rotating the elements k times in both directions -left and right.

### CODE REVIEW

**Comment by hryxna** [comment]
@hrj-star your implementation is perfect 👌
LGTM 😄.

**Comment by hrj-star** [comment]
@hryxna yes it is 😀! Thanks. 🙌

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @hrj-star ! Great work on your PR. Please consider starring the repo, if you have not already to encourage further contributions.

**Pull request merged**
