### PR TITLE
String Palindrome and Reverse Number Program added

### PR DESCRIPTION
**Pull request by Deepaksingh-rathore**

### CODE REVIEW

**Comment by Deepaksingh-rathore** [comment]
Two program added with Solution in java

**Comment by Deepaksingh-rathore** [comment]
hey @aditya109 ,
 String palindrome and reverse the number programs with solution in java added.

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @Deepaksingh-rathore ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Pull request merged**
