### PR TITLE
JS bubblesort

### PR DESCRIPTION
**Pull request by lancaster215**

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @lancaster215 ! Would you mind putting the `bubblesort.js` in `Bubblesort` folder inside `Javascript` folder?

**Comment by lancaster215** [comment]
> Hi @lancaster215 ! Would you mind putting the `bubblesort.js` in `Bubblesort` folder inside `Javascript` folder?

done. Thanks

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @lancaster215 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Pull request merged**
