### PR TITLE
Create LCM.py

### PR DESCRIPTION
**Pull request by mahendra9661**
Python Program to find the L.C.M. of two input number

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Please make put `LCM.py` under a directory called `LCM` under `Python`.

**Comment by mahendra9661** [comment]
My program is accepted ?

**Comment by aditya109** [comment]
> My program is accepted ?

As a token of appreciation, all the valid PRs are `hacktoberfest-accepted`, but to get the PRs merged, you need to follow [CONTRIBUTING.md](https://github.com/aditya109/git-osp-for-beginners/blob/master/CONTRIBUTING.md).

**Comment by aditya109** [comment]
Unfortunately, I can't merge this PR, since you haven't addressed the changes  but I am labelling this PR as `hacktoberfest-accepted` which carries the same value. Also, if you have not, consider starring this repo.

**Pull request closed without merging**
