### PR TITLE
Convert Celsius to Fahrenheit added - PR

### PR DESCRIPTION
**Pull request by govindraj111**
Convert Celsius to Fahrenheit added - Java | Problem4

note:
Decimal format precision handled

Execution steps:
Screenshot from 2020-10-06 09-56-40

### CODE REVIEW

**Comment by govindraj111** [comment]
@aditya109 Please look into this PR!

**Comment by govindraj111** [comment]
@aditya109 can you please review the PR and merge it to PR?

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @govindraj111 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Pull request merged**
