### PR TITLE
Added 2 Programs PalindromeOrNot and AnagramsOrNot

### PR DESCRIPTION
**Pull request by hryxna**
Hello, @aditya109 I have Added Both the Programs and are their solutions unique.
please review it and if you find my contribution valuable then merge it 😄.
Have a good day 😃.

### CODE REVIEW

**Comment by hryxna** [comment]
Hello, @aditya109 I would like to draw your attention to my recent pull request that I have made
could you please review it? 😅

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
> Hello, @aditya109 I would like to draw your attention to my recent pull request that I have made
> could you please review it? 😅

Yeah man, I've been just busy these past few days. That's why it takes quite a while to respond. 
Anyways, great work! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Comment by hryxna** [comment]
Thanks, @aditya109 for considering my contribution valuable to your repo.
I totally got your point about being busy sorry I disturbed you 😅.
Sure I have starred it 😄.
If there's anything else that you would like me to contribute for then just let know.
Also, I'll be updating my forked with a reverse pull request.
Thanks again 😄.

**Pull request merged**
