### PR TITLE
check anagram.c

### PR DESCRIPTION
**Pull request by parthchainani**
anagram check in c  pls check code and suggest changes

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @parthchainani ! I think you misspelt the `Angaram` directory. Please change that, otherwise the PR lgtm!

**Comment by parthchainani** [comment]
hi i have changed the name as required

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @parthchainani ! Great work on your PR ! A humble request to consider starring this repo to encourage further contributions.

**Pull request merged**
