### PR TITLE
Adding Luhn Alogorithm using JavaScript for the issue #178

### PR DESCRIPTION
**Pull request by momosetti**
This PR will add:
-  Luhn Alogrithm function using JavaScript (ES6 was implemented).
- Simple test suit using vanilla JavaScript.
and it will solve the issue #178 JavaScript part.

### CODE REVIEW

**Comment by hryxna** [comment]
Hey, @momosetti I think your implementation doesn't check whether the first digits of the entered credit-card no.
I don't know whether it's your own general implementation or you just forgot to add it 😅.

Please correct me if I'm wrong here as I don't know Javascript 😅.

Rest let's see what @aditya109 will say after reviewing it.

**Comment by aditya109** [comment]
> Hey, @momosetti I think your implementation doesn't check whether the first digits of the entered credit-card no.
> I don't know whether it's your own general implementation or you just forgot to add it 😅.
> 
> Please correct me if I'm wrong here as I don't know Javascript 😅.
> 
> Rest let's see what @aditya109 will say after reviewing it.

Hi @hryxna ! Would you mind checking if the test cases mentioned by him provided by him. I apologize leaving this work to you, but would you like to review PR related to this issue, reason being you seem quite knowledgeable with this algorithm as all. I would be great if you agreed.

**Comment by hryxna** [comment]
Don't apologise @aditya109 it's ok
I'll learn something in the process 😁

**Review by hryxna — CHANGES_REQUESTED** [review]
Hey, @momosetti I tried to run the test cases that you provided
unfortunately, the results of all the 3 are TRUE i.e they are not as you mentioned them to be.
they failed 😅.

I would like you to go through your implementation again and also kindly read the README.md again provided.

Sorry 😅.

**Comment by momosetti** [comment]
@hryxna hi, i implemented a valid luhn alogirthim just with an advanced JavaScript syntax, i can refactor it to be more easier to read.
I'll check my tests suit again.
Thank you all for the feedback.

**Review by hryxna — APPROVED** [review]
Hey, @momosetti this looks quite good 😄.
Also, I liked the way you subtracted any double-digit by 9.

Keep it up 👏🏻.
Also, I was interested in the code that you altered it a new one

Would you add that one too it would be a different & simple and advanced approach to the problem 😃?

Rest, it works as it's intended and results are also as it should be cool 😄.

@aditya109 the changes LGTM you too give your own review about it 😁.

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
> Hey, @momosetti this looks quite good 😄.
> Also, I liked the way you subtracted any double-digit by 9.
> 
> Keep it up 👏🏻.
> Also, I was interested in the code that you altered it with a new one
> 
> Would you add that one too it would be a different & simple and advanced approach to the problem 😃?
> 
> Rest, it works as it's intended and results are also as it should be cool 😄.
> 
> @aditya109 the changes LGTM you too give your own review about it 😁.

Looks RTM to me.

**Comment by aditya109** [comment]
Hi @momosetti ! Great work on your PR ! A humble request to consider starring this repo to encourage further contributions.

**Pull request merged**
