### PR TITLE
Reverse of an integer

### LINKED ISSUE #206: Reverse Integer
Reverse Integer
----------------------------------------------------------------
Given a 32-bit signed integer, reverse digits of an integer.

**Note:**
Assume we are dealing with an environment that could only store integers within the 32-bit signed integer range: [−231,  231 − 1]. For the purpose of this problem, assume that your function returns 0 when the reversed integer overflows.

------------------------------------------------------------------

**Example 1:**

Input: x = 123
Output: 321

**Example 2:**

Input: x = -123
Output: -321

**Example 3:**

Input: x = 120
Output: 21

**Example 4:**

Input: x = 0
Output: 0

------------------------------------------------------------------ 

### Constraints:

`-231 <= x <= 231 - 1`

### PR DESCRIPTION
**Pull request by RishavHimmatramka**
Reference: #206

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @RishavHimmatramka ! Please follow the [guidelines](https://github.com/aditya109/git-osp-for-beginners/blob/master/CONTRIBUTING.md) while raising the PR. Put your program inside appropriate folders.

**Comment by RishavHimmatramka** [comment]
I made the required folder. Please check.

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @RishavHimmatramka ! It seems your program file doesn't have an extensions. Please fix that.

**Comment by RishavHimmatramka** [comment]
My bad, I added the extension.

**Review by aditya109 — APPROVED** [review]
lgtm

**Comment by aditya109** [comment]
Hi @RishavHimmatramka ! Great work on your PR ! If you have not please consider starring this repo to encourage further contributions.

**Pull request merged**
