### PR TITLE
FindingLCM.py

### PR DESCRIPTION
**Pull request by Atharva0205**

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Please follow the guidelines while raising the PR. Put your program inside appropriate folders.

**Comment by Atharva0205** [comment]
> Please follow the guidelines while raising the PR. Put your program inside appropriate folders.

I am really sorry if it troubled you.....I am new to the community so I didn't knew about this.

**Comment by aditya109** [comment]
> > Please follow the guidelines while raising the PR. Put your program inside appropriate folders.
> 
> I am really sorry if it troubled you.....I am new to the community so I didn't knew about this.

It is okay. If you are really confused. Take a look at PRs which are closed as a reference and read [CONTRIBUTING.md](https://github.com/aditya109/git-osp-for-beginners/blob/master/CONTRIBUTING.md).

**Comment by aditya109** [comment]
Take a look at this PR for example. I think is #202. Look at the way she has structured her files.

**Comment by aditya109** [comment]
Unfortunately, I can't merge this PR, since you haven't addressed the changes  but I am labelling this PR as `hacktoberfest-accepted` which carries the same value. Also, if you have not, consider starring this repo.

**Pull request closed without merging**
