### PR TITLE
Luhns algorithm in Python

### PR DESCRIPTION
**Pull request by Ajordat**
Added code to implement the Luhn's algorithm in Python, as requested in the issue #178.

I have tried to follow the guidelines in the CONTRIBUTING.md file, but feel free to correct me or my code if I have made any mistake on the process.

### CODE REVIEW

**Comment by hryxna** [comment]
Hey, @Ajordat your implementation of the Algo in python is amazing 😃.
And especially your explanation about not using another sum function if the product is greater than 10 is mind-blowing.

Good work keep it up 👏🏻.

Waiting for @aditya109 to review it 😄.

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @Ajordat ! Great Work on your PR !  A humble request to star this repo to encourage further contributions.

**Comment by Ajordat** [comment]
Sure! Thank you for reviewing my work!

**Comment by hryxna** [comment]
It's really outstanding 👌🏻 @Ajordat

**Pull request merged**
