### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by xloli20**
#155

### CODE REVIEW

**Review by bhaskarsantoshk — CHANGES_REQUESTED** [review]
good work @xloli20 , but some of the directories/classes are not starting with Capital Letter, can you change them ?

**Comment by xloli20** [comment]
okay!

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @xloli20 ! There are still some directories with names starting with `Problem..`. Can you change them as well ?? Change those directories' names similar to the name of file within them.

**Review by bhaskarsantoshk — CHANGES_REQUESTED** [review]
those are needed to start with capital letters 
C++/Problem4/**h**ighestScorer.cpp
C++/SinglyLinkedList/**l**inkedList.cpp 
C++/sortedLinkedList/sortedLinkedList.cpp
playerRecord.go
Java/CountDigitsInO(1)/countDigits.java
Java/Problem6/treeProblem1.java
Java/TowerOfHanoi/towerOfHanoi.java

**Comment by aditya109** [comment]
Hi @xloli20 ! Unfortunately, I can't merge this PR, because @bhaskarsantoshk pushed a PR before you, but I am labelling this PR as `MVP` and `hacktoberfest-accepted` with an aim to recognize the efforts you have put in. You can see your name featured in the repo README.md as well.

**Comment by xloli20** [comment]
oh! sorry for the delay! 
okay great, thank you so much! @aditya109

**Pull request closed without merging**
