### PR TITLE
ZigZag Conversion #210

### PR DESCRIPTION
**Pull request by I3han**
JavaScript solution

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Please follow the guidelines while raising the PR. Put your program inside appropriate folders. The name of the directory should be should as your program-file name not `Algorithms`.

**Comment by I3han** [comment]
@aditya109 Hello Can you check the latest PR please

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @I3han ! Great work on your PR ! If you have not please consider starring this repo to encourage further contributions.

**Pull request merged**
