### PR TITLE
Problem: Check if a number is Prime or Not

### PR DESCRIPTION
**Pull request by Hackerbone**
Solution to the problem given in 
Issue #75 

If there is any improvement to do please tell! Thanks!

### CODE REVIEW

**Comment by omarobaji** [comment]
I would like to contribute to this in Java

**Comment by aditya109** [comment]
> I would like to contribute to this in Java

Hi @omarobaji ! Sure why open up a relative issue using `Programming` template and claim it for yourself by asking me in the issue. Then open up a PR and link it.

**Comment by Hackerbone** [comment]
Yea give me 5 mins

**Comment by Hackerbone** [comment]
@aditya109 pushed changes

**Comment by Hackerbone** [comment]
@aditya109  if this seems alright then pls label  it as hacktoberfest-accepted and other labels. Thanks

**Review by aditya109 — CHANGES_REQUESTED** [review]
Hi @Hackerbone ! This PR is having conflicts. Can you resolve them or better yet, close this PR and raise a fresh PR. Also please mention the correct issue hash.

**Comment by Hackerbone** [comment]
Alright I'll resend PR again

**Comment by aditya109** [comment]
Thanks @Hackerbone ! I am closing this issue then.

**Pull request closed without merging**
