### PR TITLE
Added count digits program in Java

### PR DESCRIPTION
**Pull request by ATRI2107**
Hi @aditya109 I have added the program to count the digits in an integer with a **constant time complexity** making it the code with the best runtime.

### CODE REVIEW

**Review by aditya109 — CHANGES_REQUESTED** [review]
Can you change title of the directory to something similar to that of your issue ?? Please do this and then we can go ahead and merge your commit.

**Comment by ATRI2107** [comment]
Hey @aditya109 I have changed the directory name and renamed it to Count Digits in O(1) instead of Problem 4. Do let me know if you need anything apart from that.

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by aditya109** [comment]
Hi @ATRI2107 ! Thanks for your contribution ! A humble request please consider starring the repo to encourage further contributions.

**Comment by ATRI2107** [comment]
@aditya109 sure 😁

**Pull request merged**
